version: "3"
services:
  nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - /opt/nginx/html:/etc/nginx/html
        - /opt/nginx/logs:/var/log/nginx
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
    volumes:
      - /opt/lqz:/home
  web1:
    image: django_1.11.11
    ports:
      - 8081:8080
    volumes:
      - /opt/lqz:/home
  web2:
    image: django_1.11.11
    ports:
      - 8082:8080
    volumes:
      - /opt/lqz:/home